import pandas as pd
import matplotlib.pyplot as plt
from fpdf import FPDF

# Load your dataset (replace with your CSV if needed)
df = pd.read_csv("Book1.csv")

# --- Summaries ---
print("Columns in CSV:", df.columns.tolist())
print(df.head())
# Load dataset
df = pd.read_csv("Book1.csv")

# Strip spaces and lowercase all column names
df.columns = df.columns.str.strip().str.lower()

print("Cleaned columns:", df.columns.tolist())

total_waste = df["weight_kg"].sum()
logs_count = len(df)
avg_per_day = df.groupby("date")["weight_kg"].sum().mean()

# Category-wise totals
category_summary = df.groupby("category")["weight_kg"].sum()

# Daily totals
daily_summary = df.groupby("date")["weight_kg"].sum()

# --- Charts ---
# Pie chart for category breakdown
plt.figure(figsize=(5,5))
category_summary.plot.pie(autopct="%.1f%%")
plt.title("Waste Breakdown by Category")
plt.ylabel("")
plt.savefig("category_pie.png")
plt.close()

# Bar chart for daily totals
plt.figure(figsize=(6,4))
daily_summary.plot(kind="bar")
plt.title("Daily Waste Logs (kg)")
plt.xlabel("Date")
plt.ylabel("Total (kg)")
plt.tight_layout()
plt.savefig("daily_bar.png")
plt.close()

# --- PDF Report ---
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", "B", 16)

# Title
pdf.cell(200, 10, "WasteWise Weekly Report", ln=True, align="C")

# User info
pdf.set_font("Arial", "", 12)
pdf.cell(200, 10, f"User ID: {df['user_id'][0]}", ln=True)
pdf.cell(200, 10, f"Report Period: {df['date'].min()} to {df['date'].max()}", ln=True)

# Summary stats
pdf.ln(5)
pdf.cell(200, 10, f"Total Waste Segregated: {total_waste:.2f} kg", ln=True)
pdf.cell(200, 10, f"Total Logs: {logs_count}", ln=True)
pdf.cell(200, 10, f"Average per Day: {avg_per_day:.2f} kg", ln=True)

# Category summary
pdf.ln(5)
pdf.cell(200, 10, "Category Breakdown:", ln=True)
for cat, val in category_summary.items():
    pdf.cell(200, 10, f" - {cat}: {val:.2f} kg", ln=True)

# Add charts
pdf.add_page()
pdf.cell(200, 10, "Visual Insights", ln=True, align="C")
pdf.image("category_pie.png", x=30, y=30, w=150)
pdf.add_page()
pdf.image("daily_bar.png", x=30, y=30, w=150)

# Footer
pdf.set_y(-30)
pdf.set_font("Arial", "I", 10)
pdf.cell(200, 10, "Generated by WasteWise - Automated Weekly Report", ln=True, align="C")

# Save PDF
pdf.output("weekly_report.pdf")

print("✅ PDF report generated: weekly_report.pdf")
